[package]
name = "tunics-algo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
lazy_static = "1.4.0"
rand = "0.8"
